server:
  port: 8080

database:
  file: div-dash.db
  cache: shared
  mode: rw

smtp:
  server: localhost
  port: 1025
  password: pass

paseto:
  audience: div-dash
  issuer: div-dash
  key: YELLOW SUBMARINE, BLACK WIZARDRY
  tokenValid: 24
