server:
    port: 8080

database:
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: postgres

smtp:
    server: localhost
    port: 1025
    password: pass

token:
    key: YELLOW SUBMARINE, BLACK WIZARDRY
    tokenValid: 24

iex:
    token: Tpk_dc884d96cdc34cd0bd17d035434e55ab
    baseUrl: https://sandbox.iexapis.com/stable
