version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.de
      - PGADMIN_DEFAULT_PASSWORD=pass
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - 8002:80
    links:
      - "db:database"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  postgresdata:
