// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: account_type.sql

package db

import (
	"context"
)

const listAccountTypes = `-- name: ListAccountTypes :many
SELECT account_type, label
FROM "account_type"
`

func (q *Queries) ListAccountTypes(ctx context.Context) ([]AccountType, error) {
	rows, err := q.query(ctx, q.listAccountTypesStmt, listAccountTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountType
	for rows.Next() {
		var i AccountType
		if err := rows.Scan(&i.AccountType, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
