// Code generated by sqlc. DO NOT EDIT.
// source: portfolio.sql

package db

import (
	"context"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolio (
  name, user_id
) VALUES (
  $1, $2
)
RETURNING portfolio_id, name, user_id
`

type CreatePortfolioParams struct {
	Name   string `json:"name"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.queryRow(ctx, q.createPortfolioStmt, createPortfolio, arg.Name, arg.UserID)
	var i Portfolio
	err := row.Scan(&i.PortfolioID, &i.Name, &i.UserID)
	return i, err
}

const deletePortfolio = `-- name: DeletePortfolio :exec
DELETE FROM portfolio
WHERE portfolio_id = $1
`

func (q *Queries) DeletePortfolio(ctx context.Context, portfolioID int64) error {
	_, err := q.exec(ctx, q.deletePortfolioStmt, deletePortfolio, portfolioID)
	return err
}

const getPortfolio = `-- name: GetPortfolio :one
SELECT portfolio_id, name, user_id FROM portfolio
WHERE portfolio_id = $1 LIMIT 1
`

func (q *Queries) GetPortfolio(ctx context.Context, portfolioID int64) (Portfolio, error) {
	row := q.queryRow(ctx, q.getPortfolioStmt, getPortfolio, portfolioID)
	var i Portfolio
	err := row.Scan(&i.PortfolioID, &i.Name, &i.UserID)
	return i, err
}

const listPortfolios = `-- name: ListPortfolios :many
SELECT portfolio_id, name, user_id FROM portfolio
WHERE user_id = $1
ORDER BY portfolio_id
`

func (q *Queries) ListPortfolios(ctx context.Context, userID int64) ([]Portfolio, error) {
	rows, err := q.query(ctx, q.listPortfoliosStmt, listPortfolios, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Portfolio
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(&i.PortfolioID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolio = `-- name: UpdatePortfolio :one
UPDATE portfolio
SET name = $2
WHERE portfolio_id = $1
RETURNING portfolio_id, name, user_id
`

type UpdatePortfolioParams struct {
	PortfolioID int64  `json:"portfolio_id"`
	Name        string `json:"name"`
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error) {
	row := q.queryRow(ctx, q.updatePortfolioStmt, updatePortfolio, arg.PortfolioID, arg.Name)
	var i Portfolio
	err := row.Scan(&i.PortfolioID, &i.Name, &i.UserID)
	return i, err
}
