// Code generated by sqlc. DO NOT EDIT.
// source: transaction.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO "transaction" (
  id, symbol, type, "transaction_provider", price, "date", amount, portfolio_id, side
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id
`

type CreateTransactionParams struct {
	ID                  string          `json:"id"`
	Symbol              string          `json:"symbol"`
	Type                string          `json:"type"`
	TransactionProvider string          `json:"transaction_provider"`
	Price               int64           `json:"price"`
	Date                time.Time       `json:"date"`
	Amount              decimal.Decimal `json:"amount"`
	PortfolioID         string          `json:"portfolio_id"`
	Side                string          `json:"side"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (string, error) {
	row := q.queryRow(ctx, q.createTransactionStmt, createTransaction,
		arg.ID,
		arg.Symbol,
		arg.Type,
		arg.TransactionProvider,
		arg.Price,
		arg.Date,
		arg.Amount,
		arg.PortfolioID,
		arg.Side,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM "transaction"
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteTransactionStmt, deleteTransaction, id)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, symbol, type, transaction_provider, price, date, amount, portfolio_id, side FROM "transaction"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.queryRow(ctx, q.getTransactionStmt, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Type,
		&i.TransactionProvider,
		&i.Price,
		&i.Date,
		&i.Amount,
		&i.PortfolioID,
		&i.Side,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, symbol, type, transaction_provider, price, date, amount, portfolio_id, side FROM "transaction"
WHERE portfolio_id = $1
ORDER BY date DESC
`

func (q *Queries) ListTransactions(ctx context.Context, portfolioID string) ([]Transaction, error) {
	rows, err := q.query(ctx, q.listTransactionsStmt, listTransactions, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Type,
			&i.TransactionProvider,
			&i.Price,
			&i.Date,
			&i.Amount,
			&i.PortfolioID,
			&i.Side,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
